syntax = "proto3";

package golinks;
option go_package = "github.com/kellegous/golinks";

import "google/protobuf/timestamp.proto";

service GoLinks {
  rpc Put(PutReq) returns (PutRes);
  rpc Get(GetReq) returns (GetRes);
  rpc Delete(DeleteReq) returns (DeleteRes);
  rpc Expand(ExpandReq) returns (ExpandRes);
  rpc List(ListReq) returns (ListRes);
}

message PutReq { Link link = 1; }
message PutRes { Link link = 1; }

message GetReq { string prefix = 1; }
message GetRes { Link link = 1; }

message DeleteReq { string prefix = 1; }
message DeleteRes { Link link = 1; }

message ListReq {
  string after = 1;
  uint32 limit = 2;
}
message ListRes {
  repeated Link links = 1;
  string last_prefix = 2;
}

message ExpandReq {
  Link link = 1;
  string uri = 2;
}
message ExpandRes {
  string url = 1;
  uint32 match_index = 2;
}

message Link {
  string prefix = 1;
  repeated Match matches = 2;
  google.protobuf.Timestamp created_at = 3;
}

message Match {
  string pattern = 1;
  string url = 2;
}