package web

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/HALtheWise/o-links/_vendor-20180306154129/github.com/syndtr/goleveldb/leveldb/errors"
)

func normalizeName(name string) (string, error) {
	if name == "" {
		// This should never happen on a POST, a name should have been autogenerated before this function was called.
		return "", errors.New("Name not provided")
	}

	if isBannedName(name) {
		return "", errors.New(fmt.Sprintf(`"%s" is a banned name, try another`, name))
	}

	// Normalize the name, converting everything to lowercase and all non-word characters to single hyphens
	name = strings.ToLower(name)

	name = regexp.MustCompile(`[\W_]+`).ReplaceAllString(name, "-")
	name = strings.Trim(name, "-")

	return name, nil
}
